SELECT *, MIN(WEIGHT) 
FROM ITEMS

SELECT W. WNAME, C.CITY
FROM WAREHOUSES W,CITIES C
WHERE W.CID = C.CID AND C.CITY = 'Pune'

SELECT  C.CNAME, O.ONO, O.ODATE,  I.DESCRIPTION
FROM ITEMSORDERS IO, ITEMS I, ORDERS O, CUSTOMER C
WHERE IO.ITEMNO = I.ITEMNO AND IO.ONO = O.ONO AND O.CNO = C.CNO AND CNAME = 'Mr Patil'
ORDER BY O.ONO

SELECT * , MAX(NO)
FROM ( 
  SELECT W.WID, W.WNAME, COUNT(W.WID) NO
  FROM STORES S, WAREHOUSES W
  WHERE S.WID = W.WID
  GROUP BY W.WID
  ORDER BY W.WID
)

SELECT DESCRIPTION, MIN(TIMESORDER) 'TIMES ORDER'
FROM (
  SELECT  IO.IOID, O.ONO, I.ITEMNO, I.DESCRIPTION, COUNT(I.ITEMNO) TIMESORDER
  FROM ITEMSORDERS IO, ITEMS I, ORDERS O
  WHERE IO.ITEMNO = I.ITEMNO AND IO.ONO = O.ONO 
  GROUP BY I.ITEMNO
  ORDER BY O.ONO
  )

SELECT  C.CNO, C.CNAME, O.ODATE, I.DESCRIPTION, I.WEIGHT, I.COST
FROM ITEMSORDERS IO, ITEMS I, ORDERS O, CUSTOMER C
WHERE IO.ITEMNO = I.ITEMNO AND IO.ONO = O.ONO AND O.CNO = C.CNO
ORDER BY C.CNO, O.ODATE